apiVersion: v1
kind: Service
metadata:
  name: grocery-service-1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      
  selector:
    app: grocery-api
   
