apiVersion: apps/v1 

kind: Deployment

metadata:

  #name: postgres-deployment-g43
  name: {{.Values.db.name}}
spec:

  replicas: 1

  selector:

    matchLabels:

      app: postgres

  template:

    metadata:

      labels:

        app: postgres

    spec:

      containers:

      - name: {{.Values.dbcontainer.name}}

        image: postgres:13.1-alpine

        imagePullPolicy: {{.Values.dbimage.pullPolicy}}

        ports:

          - containerPort: {{.Values.dbcontainerPort.port}}

        envFrom:

          - configMapRef:

              name: postgres-config-g43

        env:

          - name: POSTGRES_PASSWORD

            valueFrom:

              secretKeyRef:

                name: postgres-secret-g43

                key: POSTGRES_PASSWORD

        volumeMounts: 

          - mountPath: /var/lib/postgresql/data

            name: postgredb

      volumes:

      - name: postgredb

        persistentVolumeClaim:

          claimName: postgres-pv-claim-g43


