apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: developer-binding
subjects:
  - kind: User
    name: calvin
    apiGroup: rbac.authorization.k8s.io
#  - kind: User
#    name: yuna
#    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
