apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: pod-reader-binding
subjects:
  - kind: User
    name: calvin
    apiGroup: rbac.authorization.k8s.io
  #- kind: User
  #  name: zzy
  #  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-watcher
  apiGroup: rbac.authorization.k8s.io
