apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-deployment
  labels:
    app: grocery-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grocery-api
      version:v1.0.0
  template:
    metadata:
      labels:
        app: grocery-api
        version:v1.0.0
    spec:
      containers:
      - name: grocery-api-container
        image: us-east1-docker.pkg.dev/poised-rocked-413209/grocery/123
        ports:
        - containerPort: 5000
   
