apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/issuer: my-ca-issuer-1
    cert-manager.io/common-name: mygrocery-g43-1.com
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: my-ingress-1
  namespace: default
spec:
  rules:
  - host: mygrocery-g43-1.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: grocery-service-1
            port:
              number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - mygrocery-g43-1.com
    secretName: myingress-cert-1 # < cert-manager will store the created certificate in this secret.
