apiVersion: v1
kind: Service
metadata:
  name: postgres-service-g43-1
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    #- port: 5432
    #  nodePort: 30001
    - port: {{.Values.dbservice.port}}
      nodePort: {{.Values.dbservice.port}}
  selector:
    app: postgres
