kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-1
  labels:
    type: local
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
#   path: "/opt/postgres/data"
    path: "/var/posgres"
