apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: default
  name: developer-1
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployment", "configmaps", "namespaces"]
    verbs: ["get", "watch", "list","create","update"]
