apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca-1
  namespace: default
spec:
  isCA: true
  commonName: my-selfsigned-ca-1
  secretName: root-secret-1
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer-1
    kind: ClusterIssuer
    group: cert-manager.io
