apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-viewer-binding-1
subjects:
  - kind: User
    name: calvin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-viewer-1
  apiGroup: rbac.authorization.k8s.io
